---
- hosts: [ansible_clients]
  vars:
    ansible_python_interpreter: /usr/bin/python
  become: True
  tasks:
    - debug: var=ansible_host
    - name: Install python pip
      yum:
        name: python-pip
        state: present
    - name: Install docker
      yum:
        name: docker
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Start the container
      docker_container:
        name: dockeransible_pipeline
        image: "pavanshivanand/dockeransible_pipeline:{{DOCKERTAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8888:8080
